version: '3.5'
services:
  service:
    container_name: gateway
    image: twentiapp/dev:gateway
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - twenti
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
    restart: always
    environment:
      SERVICE_NAME: gateway
      PROFILE: dev
      CONFIG_SERVER_URI: http://config:8888
networks:
  twenti:
    external: true