version: '3.5'
services:
  service:
    container_name: gateway
    image: twentiapp/dev:gateway
    build:
      context: ""
      dockerfile: ./Dockerfile
    expose:
      - 8765
    ports:
      - "8080:8080"
    networks:
      - twenti
    restart: always
    environment:
      SERVICE_NAME: gateway
      PROFILE: dev
      CONFIG_SERVER_URI: http://config:8888
networks:
  twenti:
    external: true