version: '3.5'
services:
  service:
    container_name: eureka
    image: twentiapp/dev:eureka
    expose:
      - 8761
    ports:
      - "8761:8761"
    networks:
      - twenti
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
    restart: always
    environment:
      SERVICE_NAME: eureka
      PROFILE: dev
      CONFIG_SERVER_URI: http://config:8888
networks:
  twenti:
    external: true