version: '3'
services:
  service:
    container_name: auth
    image: twentiapp/dev:auth
    build:
      context: "../"
      dockerfile: auth/Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - twenti
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
    restart: always
    environment:
      SERVICE_NAME: auth
      PROFILE: dev
      CONFIG_SERVER_URI: http://config:8888
networks:
  twenti:
    external: true