version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - twenti
    deploy:
      resources:
        limits:
          cpus: 0.10
          memory: 100M
networks:
  twenti:
    external: true