version: '3'
services:
  redis:
    container_name: redis
    image: redis
    networks:
      - twenti
    deploy:
      resources:
        limits:
          cpus: 0.10
          memory: 100M
networks:
  twenti:
    external: true