version: '3'
services:
  redis:
    container_name: redis
    image: redis
    networks:
      - twenti
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
networks:
  twenti:
    external: true