version: '3.5'
services:
  service:
    container_name: admin
    image: admin
    build:
      context: ""
      dockerfile: ./Dockerfile
    expose:
      - 8765
    ports:
      - "8765:8765"
    networks:
      - twenti
    restart: always
    environment:
      SERVICE_NAME: admin
      PROFILE: dev
      CONFIG_SERVER_URI: http://config:8888
networks:
  twenti:
    external: true