name: Deploy to EC2-dev

on:
  push:
    branches:
      - main

env:
  INSTANCE_IP: ${{ secrets.INSTANCE_IP_DEV }}
  PEM_FILE: ${{ secrets.SSH_PRIVATE_KEY_DEV }}

jobs:
  deploy-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      - name: Copy Docker Compose files
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.INSTANCE_IP_DEV }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          source: ./config/docker-compose.yml
          target: /home/ec2-user/docker-compose-config

      - name: SSH into EC2 instance and start containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.INSTANCE_IP_DEV }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          script: |
            cd /home/ec2-user/docker-compose-config
            docker-compose -f auth/docker-compose.yml up -d
