name: Deploy-all

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_eureka:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy Eureka
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Deploy Eureka
        uses: ./.github/workflows/deploy-eureka.dev.yml