name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo apt-get install -y docker-compose

    - name: Configure SSH keys
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY_DEV}}" > key.pem
        chmod 600 key.pem
        ssh-add key.pem

    - name: Deploy config container
      run: |
        ssh -o "StrictHostKeyChecking=no" ec2-user@${{ secrets.INSTANCE_IP_DEV }} "cd /path/to/config && docker-compose up -d"
