name: Deploy-all

on:
  push:
    branches:
      - main

env:
  INSTANCE_IP: ${{ secrets.INSTANCE_IP_DEV }}
  PEM_FILE: ${{ secrets.SSH_PRIVATE_KEY_DEV }}

jobs:
  deploy-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Build project with Maven
        run: mvn clean package -f config/pom.xml

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
